Dockerfile: set locale to UTF-8
Fixes:
ERROR:  OE-core's config sanity checker detected a potential misconfiguration.
    Either fix the cause of this error or at your own risk disable the checker (see sanity.conf).
    Following is the list of potential problems / advisories:

    You system needs to support the en_US.UTF-8 locale.


Signed-off-by: Mirza Krak <mirza.krak@endian.se>